export default {
  "widget.hero": "hero",
  "widget.features": "features",
  "widget.testimonial": "testimonial",
  "widget.callToAction": "callToAction",
  "widget.cta": "cta",
  "widget.cta2": "cta2",
  "widget.cta3": "cta3",
  "widget.cta4": "cta4",
  "widget.cta5": "cta5",
  "widget.cta6": "cta6",
  "widget.cta7": "cta7",
  "widget.cta8": "cta8",
  "widget.cta9": "cta9",
  "widget.cta10": "cta10",
  "widget.cta11": "cta11",
  "widget.cta12": "cta12",
  "widget.cta13": "cta13",
  "widget.cta14": "cta14",
  "widget.cta15": "cta15",
  "widget.cta16": "cta16",
}